"use client";

import Link from "next/link";
import { ArrowRight, BriefcaseBusiness, Cake, Heart, Users } from "lucide-react";
import { motion } from "framer-motion";
import { SafeImage } from "@/components/ui/SafeImage";
import type { HotelData } from "@/data/hotels";

export function BanquetSection({ hotel }: { hotel: HotelData }) {
  const events = [[Heart,"Weddings"],[BriefcaseBusiness,"Corporate"],[Cake,"Birthdays"],[Users,"Social Gatherings"]] as const;
  return <section aria-labelledby="banquet-title" className="bg-[#f8f3e9] px-6 py-24 sm:px-10 lg:py-36"><div className="mx-auto grid max-w-[1280px] items-center gap-14 lg:grid-cols-[1.05fr_.95fr] lg:gap-20"><motion.div initial={{ opacity:0,x:-25 }} whileInView={{opacity:1,x:0}} viewport={{once:true}} className="relative aspect-[4/3] overflow-hidden rounded-[28px] bg-[#e4e9e4]"><SafeImage src={`/images/hotels/${hotel.slug}/banquet.webp`} alt={`Banquet venue at ${hotel.name}`} fill sizes="(max-width:1023px) 100vw, 52vw" className="object-cover" fallbackLabel="Banquets & events"/></motion.div><div><p className="text-[10px] font-semibold uppercase tracking-[.4em] text-[var(--emerald)]">Gather Beautifully</p><h2 id="banquet-title" className="mt-5 font-[family-name:var(--font-cormorant)] text-[clamp(2.6rem,5vw,4rem)] font-medium leading-[1.02] text-[#173c2b]">Banquets & Events</h2><p className="mt-7 text-[15px] leading-8 text-[#647068]">Flexible spaces, thoughtful catering and attentive coordination create an assured setting for meaningful occasions. Our team helps shape every detail around your gathering.</p><div className="mt-8 grid grid-cols-2 gap-3">{events.map(([Icon,label])=><div key={label} className="flex items-center gap-3 text-[11px] text-[#4f5e55]"><Icon size={17} className="text-[var(--emerald)]"/>{label}</div>)}</div><div className="mt-9 rounded-[20px] border border-[#b69b60]/30 bg-white p-6"><p className="text-[9px] uppercase tracking-[.16em] text-[#8c7a51]">Venue capacity</p><strong className="mt-2 block font-[family-name:var(--font-cormorant)] text-3xl text-[#173c2b]">{hotel.banquetCapacity}</strong></div><Link href={`https://wa.me/919179191110?text=${encodeURIComponent(`I would like to enquire about an event at ${hotel.name}.`)}`} className="group mt-7 flex h-13 w-full items-center justify-center gap-2 rounded-full bg-[var(--emerald)] px-7 text-[10px] font-semibold uppercase tracking-[.12em] text-white sm:w-fit">Enquire Now <ArrowRight size={15} className="transition-transform group-hover:translate-x-1"/></Link></div></div></section>;
}
