"use client";

import { useEffect, useState } from "react";
import { ChevronLeft, ChevronRight, X } from "lucide-react";
import { AnimatePresence, motion } from "framer-motion";
import { SafeImage } from "@/components/ui/SafeImage";

const gallery=["Wedding","Corporate","Birthday","Decoration","Dining","Stage","Reception"];
export function BanquetGallery(){const[active,setActive]=useState<number|null>(null);useEffect(()=>{if(active===null)return;const fn=(e:KeyboardEvent)=>{if(e.key==="Escape")setActive(null);if(e.key==="ArrowRight")setActive(v=>v===null?0:(v+1)%gallery.length);if(e.key==="ArrowLeft")setActive(v=>v===null?0:(v-1+gallery.length)%gallery.length)};document.body.style.overflow="hidden";window.addEventListener("keydown",fn);return()=>{document.body.style.overflow="";window.removeEventListener("keydown",fn)}},[active]);return <section aria-labelledby="banquet-gallery-title" className="bg-[#f8f3e9] px-6 py-24 sm:px-10 lg:py-32"><div className="mx-auto max-w-[1280px]"><p className="text-[10px] font-semibold uppercase tracking-[.4em] text-[var(--emerald)]">Celebrations In Detail</p><h2 id="banquet-gallery-title" className="mt-5 font-[family-name:var(--font-cormorant)] text-[clamp(2.7rem,5vw,4.2rem)] font-medium text-[#173c2b]">Banquet Gallery</h2><div className="mt-12 grid auto-rows-[220px] gap-4 sm:grid-cols-2 lg:grid-cols-4">{gallery.map((label,i)=><button key={label} onClick={()=>setActive(i)} aria-label={`Open ${label} gallery image`} className={`group relative overflow-hidden rounded-[20px] bg-[#e4e9e4] ${i===0||i===4?"sm:row-span-2":""} ${i===2?"lg:col-span-2":""}`}><SafeImage src={`/images/banquet/gallery/${label.toLowerCase()}.webp`} alt={`${label} celebration at Annapurna banquets`} fill sizes="(max-width:640px) 100vw, 50vw" className="object-cover transition-transform duration-700 group-hover:scale-105" fallbackLabel={label}/><span className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/65 to-transparent px-5 pb-4 pt-12 text-left text-[10px] font-semibold uppercase tracking-[.14em] text-white">{label}</span></button>)}</div></div><AnimatePresence>{active!==null&&<motion.div role="dialog" aria-modal="true" aria-label={`${gallery[active]} banquet image`} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-[120] grid place-items-center bg-black/90 p-5"><div className="relative h-[80vh] w-full max-w-[1100px]"><SafeImage src={`/images/banquet/gallery/${gallery[active].toLowerCase()}.webp`} alt={`${gallery[active]} event`} fill sizes="100vw" className="object-contain" fallbackLabel={gallery[active]} fallbackClassName="bg-[#173c2b] text-white"/></div><button autoFocus onClick={()=>setActive(null)} aria-label="Close gallery" className="absolute right-5 top-5 grid size-12 place-items-center rounded-full border border-white/25 text-white"><X/></button><button onClick={()=>setActive((active-1+gallery.length)%gallery.length)} aria-label="Previous image" className="absolute left-4 text-white"><ChevronLeft/></button><button onClick={()=>setActive((active+1)%gallery.length)} aria-label="Next image" className="absolute right-4 text-white"><ChevronRight/></button></motion.div>}</AnimatePresence></section>}
