"use client";

import Link from "next/link";
import { ArrowDown, ArrowRight } from "lucide-react";
import { motion } from "framer-motion";
import { SafeImage } from "@/components/ui/SafeImage";

export function BanquetHero() {
  return <section aria-labelledby="banquet-hero-title" className="relative flex min-h-[700px] h-[85svh] items-center overflow-hidden bg-[#173c2b]"><SafeImage src="/images/banquet/hero.webp" alt="An elegant Annapurna banquet hall prepared for a celebration" fill priority sizes="100vw" className="object-cover" fallbackLabel="Banquet & events" fallbackClassName="bg-[#173c2b] text-white/65"/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(8,20,14,.75),rgba(8,20,14,.35))]"/><motion.div initial={{opacity:0,y:28}} animate={{opacity:1,y:0}} transition={{duration:.7}} className="relative z-10 mx-auto w-full max-w-[1400px] px-6 pt-24 text-white sm:px-10"><nav aria-label="Breadcrumb" className="flex gap-2 text-[9px] font-semibold uppercase tracking-[.16em] text-white/65"><Link href="/">Home</Link><span>/</span><span aria-current="page">Banquet</span></nav><p className="mt-10 text-[10px] font-semibold uppercase tracking-[.4em] text-[#d8c38a]">Banquet & Events</p><h1 id="banquet-hero-title" className="mt-6 max-w-[900px] font-[family-name:var(--font-cormorant)] text-[clamp(3.5rem,8vw,7rem)] font-medium leading-[.9] tracking-[-.04em]">Celebrate Every Moment <span className="block text-[#d8c38a]">with Elegance</span></h1><p className="mt-7 max-w-[680px] text-[14px] leading-7 text-white/78 sm:text-[16px]">From weddings and receptions to engagements, birthdays, conferences and corporate gatherings, Annapurna creates composed spaces where every important moment feels genuinely cared for.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="#venues" className="group flex h-14 items-center justify-center gap-2 rounded-full bg-[var(--emerald)] px-8 text-[10px] font-semibold uppercase tracking-[.12em] text-white">Book a Venue <ArrowRight size={15} className="transition-transform group-hover:translate-x-1"/></Link><Link href="#enquiry" className="flex h-14 items-center justify-center rounded-full border border-white/30 bg-white/8 px-8 text-[10px] font-semibold uppercase tracking-[.12em] text-white backdrop-blur-md">Enquire Now</Link></div></motion.div><motion.a href="#event-categories" aria-label="Scroll to event categories" animate={{y:[0,7,0]}} transition={{duration:2,repeat:Infinity}} className="absolute bottom-7 left-1/2 z-10 text-white/60"><ArrowDown/></motion.a></section>;
}
