"use client";

import Link from "next/link";
import { ArrowRight, Check, Users } from "lucide-react";
import { motion } from "framer-motion";
import { SafeImage } from "@/components/ui/SafeImage";
import type { BanquetVenue } from "@/data/banquets";

export function FeaturedVenues({ venues }: { venues: BanquetVenue[] }) {
  return <section id="venues" aria-labelledby="venues-title" className="bg-[#f8f3e9] px-6 py-24 sm:px-10 lg:py-36"><div className="mx-auto max-w-[1280px]"><div className="max-w-[720px]"><p className="text-[10px] font-semibold uppercase tracking-[.4em] text-[var(--emerald)]">Featured Venues</p><h2 id="venues-title" className="mt-5 font-[family-name:var(--font-cormorant)] text-[clamp(2.7rem,5vw,4.3rem)] font-medium leading-[1.02] text-[#173c2b]">Two settings. One standard of care.</h2></div><div className="mt-16 space-y-24">{venues.map((venue,index)=><motion.article id={venue.slug} key={venue.slug} initial={{opacity:0,x:index%2?-28:28}} whileInView={{opacity:1,x:0}} viewport={{once:true,amount:.15}} className="grid items-center gap-8 lg:grid-cols-2 lg:gap-16"><div className={`relative aspect-[16/11] overflow-hidden rounded-[28px] bg-[#e4e9e4] shadow-[0_25px_70px_rgba(23,60,43,.14)] ${index%2?"lg:order-2":""}`}><SafeImage src={venue.image} alt={`${venue.name} prepared for an elegant event`} fill sizes="(max-width:1023px) 100vw, 50vw" className="object-cover" fallbackLabel={venue.name}/></div><div><p className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.16em] text-[#987a40]"><Users size={14}/>{venue.capacity}</p><h3 className="mt-5 font-[family-name:var(--font-cormorant)] text-[clamp(2.6rem,5vw,4rem)] font-medium leading-none text-[#173c2b]">{venue.name}</h3><p className="mt-6 text-[14px] leading-7 text-[#647068]">{venue.description}</p><ul className="mt-7 grid gap-3 sm:grid-cols-2">{venue.highlights.map(item=><li key={item} className="flex items-center gap-2 text-[11px] text-[#59665e]"><Check size={14} className="text-[var(--emerald)]"/>{item}</li>)}</ul><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href={`#${venue.slug}-comparison`} className="flex h-12 items-center justify-center gap-2 rounded-full border border-[#173c2b]/15 px-6 text-[10px] font-semibold uppercase tracking-[.1em] text-[#173c2b]">View Details</Link><Link href={`https://wa.me/917566500040?text=${encodeURIComponent(`I would like to book ${venue.name}.`)}`} className="group flex h-12 items-center justify-center gap-2 rounded-full bg-[var(--emerald)] px-6 text-[10px] font-semibold uppercase tracking-[.1em] text-white">Book This Venue <ArrowRight size={14} className="transition-transform group-hover:translate-x-1"/></Link></div></div></motion.article>)}</div></div></section>;
}
